### PR TITLE
Release listen socket if error was

### PR DESCRIPTION
**Pull request by avbelov23**
https://github.com/tempesta-tech/tempesta/issues/1314

### CODE REVIEW

**Comment by ikoveshnikov** [comment]
> Some modules do clean up if startup fails (tfw_filter_start), some do not (tfw_sock_srv_start).

Yeah, thats a real mess. The `TfwMod` description must contain description of the of the module contract: when the cleanup functions are called and when - not. Since now only properly started modules are stopped, some doesn't invoke cleanup and the #1314 issue is actually deeper than it seemed.

> But I'd prefer not doing that — to keep the clear semantics: one needs to stop only that what was properly started. 

I don't see there real difference here. Anyway, clean up on the failed start is mostly the same as the `stop()` function.

**Comment by i-rinat** [comment]
> I don't see there real difference here. Anyway, clean up on the failed start is mostly the same as the stop() function.

Yeah, if there were a significant differences I definitely would've described them. Instead, it's just a personal preference. I like it when APIs move complexity out of my way, thus reducing a number of things I have to worry about. 

> The TfwMod description must contain description of the of the module contract: when the cleanup functions are called and when - not.

I insist on not doing that. We should select one way and change remaining code to follow that. There is no benefit in having that flexibility, as it's an internal API, and we have the freedom to do as we please there.

**Comment by ikoveshnikov** [comment]
@avbelov23 Have you looked to other modules? do we have the same issue anywhere else?

**Comment by avbelov23** [comment]
What is the issue?

>Some modules do clean up if startup fails (tfw_filter_start), some do not (tfw_sock_srv_start).
Is this issue?

**Comment by ikoveshnikov** [comment]
Yes, that is.

**Comment by avbelov23** [comment]
I propose to fix the issues in other modules with separate PR

**Comment by avbelov23** [comment]
DONE

**Comment by avbelov23** [comment]
There is no issue in `sock_srv`. The release of resources occurs during the removal of servers from groups

**Pull request merged**
