### PR TITLE
Solution for 2099

### PR DESCRIPTION
**Pull request by biathlon3**

### CODE REVIEW

**Comment by biathlon3** [comment]
The definition of vhost was after checking http_hdr_cnt.

**Comment by enuribekov-tempesta** [comment]
LGTM

**Review by enuribekov-tempesta — APPROVED** [review]
LGTM

**Comment by EvgeniiMekhanik** [comment]
PR doesn't work. I create tests for this PR https://github.com/tempesta-tech/tempesta-test/pull/609 and they don't pass. tfw_cfgop_frang_glob_in_vhost should be used in tfw_vhost_frang_specs structure for settings which are defined only globally. As i see you should add appropriate settings to tfw_frang_glob_reconfig (FrangGlobCfg) structure

**Review by EvgeniiMekhanik — CHANGES_REQUESTED** [review]
PR doesn't work. I create tests for this PR https://github.com/tempesta-tech/tempesta-test/pull/609 and they don't pass. tfw_cfgop_frang_glob_in_vhost should be used in tfw_vhost_frang_specs structure for settings which are defined only globally. As i see you should add appropriate settings to tfw_frang_glob_reconfig (FrangGlobCfg) structure

**Review by EvgeniiMekhanik — APPROVED** [review]

**Comment by EvgeniiMekhanik** [comment]
LGTM. Please update WIKI, that this settings are only globals

**Pull request merged**
