### PR TITLE
Implement WINDOW_UPDATE support on ingress traffic

### PR DESCRIPTION
**Pull request by EvgeniiMekhanik**
Change tempesta INITIAL_WINDOW_SIZE to 65536
(default value described in RFC).

### CODE REVIEW

**Comment by EvgeniiMekhanik** [comment]
Since we don't support big requests and responses now i have no idea how to test this PR

**Review by krizhanovsky — APPROVED** [review]
LGTM. We discussed today that there are tests employing WINDOW_UPDATE, so it seems we test the logic. Also since the default window now is smaller (64KB instead of 2GB), our tests for large bodies (like 2MB) will hit the logic. 

@RomanBelozerov could you please confirm that my conclusions are correct? In general, could you please make sure that we have tests for WINDOW_UPDATE.

**Review by const-t — APPROVED** [review]
LGTM

**Comment by RomanBelozerov** [comment]
> LGTM. We discussed today that there are tests employing WINDOW_UPDATE, so it seems we test the logic. Also since the default window now is smaller (64KB instead of 2GB), our tests for large bodies (like 2MB) will hit the logic.
> 
> @RomanBelozerov could you please confirm that my conclusions are correct? In general, could you please make sure that we have tests for WINDOW_UPDATE.

Yes, you're right and we have tests to check WINDOW_UPDATE in [PR-550](https://github.com/tempesta-tech/tempesta-test/pull/550) and also all tests with request body greater than 64 kB check it (`t_long_body` directory in tempesta-test)

**Pull request merged**
